### PR TITLE
 Add poweron architecture ppc64le to travis build

### PR DESCRIPTION
**Pull request by asellappen**
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing, For more info please tag @gerrith3.

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

I don't understand the relation between the CI of a DNS API client and ppc64le.
Could you explain?

**Comment by asellappen** [comment]
We typically build applications for customers and ISVs, and while we don't use this package directly, we do count on all of the packages in debian/ubuntu to build other packages. So we more likely have this as a second or third level dependency and couldn't tell you explicitly which features we use or our usage model.

**Comment by asellappen** [comment]
Hope the above explains your clarification

**Comment by asellappen** [comment]
please let me know anyuthing need to be done to get PR meagered ?

**Comment by asellappen** [comment]
any update on this pls.Please let me know if you need any explanation .

**Comment by ldez** [comment]
> We typically build applications for customers and ISVs, and while we don't use this package directly, we do count on all of the packages in debian/ubuntu to build other packages. So we more likely have this as a second or third level dependency and couldn't tell you explicitly which features we use or our usage model.

In summary:
- you are working for IBM
- you are building commercial products
- you are not a direct user and you don't know which element require this lib
- you want that [all the world add ppc64le in their CI](https://github.com/pulls?q=is%3Apr+archived%3Afalse+author%3Aasellappen+is%3Aopen+Add+poweron+architecture+ppc64le+to+travis+build) because you are not able the validate the compatibility by yourself
- you want that maintenace of the compatiblity with ppc64le to be handle by the current open-source maintainers and contributors of the libs

From my point of view, ppc64 is an edge case, strongly related to IBM, as I don't have ppc64le locally if there is an issue I will not be able to debug easily without Travis, and it's more work for me.

Maybe I'm wrong, maybe I missed something, but currently, I'm puzzled about your PR.

**Comment by gerrith3** [comment]
Sorry - @ldez but not completely correct here.  My team is responsible for all open source components that customers/ISVs use, and we also do a fair bit of upstream work to enable packages for distributions.  Yes, we work for IBM.  Yes, IBM builds commercial products, although this effort is completely unrelated to those (remember, 300,000+ IBMers with a lot of different goals).  We build open source packages for customers/ISVs, often fixing issues on ppc64le, upstreaming them, and when necessary publishing build scripts for customers - primarily to help them resolve dependencies on ppc64le platforms.  You can see an example of those scripts on github in ppc64le/build-scripts as one example.

As far as validating 10,000,000 github projects by ourselves, you are right, we can't.  The fact that people have been developing on Intel for a very long time means there is a lot of investment there that we can't match, but we also have customers running some of the largest applications and platforms on Power and they are hoping to have the same capabilities on Power that they have on Intel, only with the addition of the enterprise hardening features that our platform provides, and additional scalability/performance.  We are effectively operating on their behalf, expanding the ecosystem from a "meets min" approach to a broader embracing of open source - as is part of the very long term IBM DNA.  This is one example of the billions of dollars we have put into open source over the years, expanding the architecture choices, the open source package choices, and making things as simple for the end user.

And yes, the open source way has been for the past 40-50 years that I've been involved with it, to expand the capabilities of projects to embrace new models of operation, be it some of my first experiences in contributing some of the first code to BSD, to our work in scalability of Linux, to Eclipse, Apache, Linux Foundation, etc. etc. etc.

ppc64le is probably a lot less of an edge case than you realize, with much of the Global 1000 using them in their data centers to provide the services that most of us depend on every day.  Yes, typical developers don't see those highly closed environments or the people from them - we try to broker a lot of their needs since they are typically not allowed to interact freely in open source.  And, in terms of additional maintenance cost, ppc64le is in many ways identical to x86-64.  There are corner cases, which is why we do so much testing up front and we we find it absolutely a requirement to provide free access for testing and such to the open source community.  Also, with the Open Power Foundation, there are a number of other vendors providing Power hardware now, including companies like Raptor with the more desktop sized machines as compared to what IBM builds.

Finally, even if you don't have a ppc64le box locally, you can always request a free VM from our partner, OSL, via https://osuosl.org/services/powerdev/ which provides VM access as well as built in Jenkins support.  And we do work on other projects that you are part of, e.g. traefik both for use on its own and as part of the red hat application stack in the future.

**Comment by ldez** [comment]
I really would have liked a slightly more verbose and clearer description of the context and purpose at the opening of the PR.

To remove all ambiguities, for me, commercial software has customers and open-source software has users, I talked about  "commercial products" because of the use of the term "customers".

I like a clear and direct approach, the goal of this PR wasn't clear for me, I appreciate your answer.

I still have some questions:
- If I understood well, the project is a transitive dependency of a project which is packaged, at the time of the creation of this package you are not able to validate the construction for your architecture?
- What exactly and precisely is the advantage for you, that this lib uses ppc64le in its CI?
- If I merge this PR, how do you check that I don't remove this change in the future?
- How this kind of "chain of trust" works?

**Comment by ldez** [comment]
@asellappen @gerrith3 do you have some anwsers?

**Comment by gerrith3** [comment]
@ldez apologies for the delay in responding here.  Customers is a broad term, including all users of, say, Ubuntu, e.g.:

sudo apt-cache search goinwx
golang-github-nrdcg-goinwx-dev - INWX Go API client

This was from a Power server.  Ubuntu/Debian and other distros already build this on Power servers, typically provided by IBM to those communitiies.  They build as part of each release, and the machines have a habit of being underutilized a lot of the time, plus need to be updated frequently.  We are trying to move all builds and testing into the cloud where capacity can be managed much more intelligently, much like GH Actions and Azure today (although Azure does not have Power hardware).

Our goal is to ensure that top of tree is current on Power, including all releases built, in advance of any distribution builds.  Over time, they will move to the cloud as well, and it will be much easier if they don't have to port/validate if there has been a regression.  This also helps (part of our "advantage") to validate the entire stack, including the Travis environment, things like golang and dependencies, general application use, etc.  Sometimes we have applications that are newer and require updates from what is in the distro, hence we will rebuild/port top of tree when we can.

As far as you adding it now and removing it later, well, that is us trusting that you are running a typical open source community and responsive to your users.  That is up to you as to how you handle it.  And I missed your question about "chain of trust" in tihs context?  There is nothing in this process that depends on, uses, or requires a chain of trust in the security sense.  We do trust that you as a maintainer are above board, up front, and interesting in building your community.

**Comment by ldez** [comment]
I still don't undestand why the validation is not performed during the packaging of `golang-github-nrdcg-goinwx-dev`.

But anyway, I will not spend more time on this, I think that I understand your approach better even if everything doesn't seem clear to me.

Maybe the [recent changes of the Travis billing](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) will impact the capacity of the OSS community to handle this kind of need.

I will merge this PR, thank you for your time and your explanations.

**Comment by gerrith3** [comment]
I provide Travis CI with the Power hardware, so I think we will be fine there.  ;)

**Pull request merged**
